apiVersion: apps/v1
kind: Deployment
metadata:
  name: brock-bus
  labels:
    app: brock-bus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: brock-bus
  template:
    metadata:
      labels:
        app: brock-bus
    spec:
      containers:
      - name: brock-bus
        image: gcr.io/radical-sloth/brock-bus
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "10Mi"
            cpu: "10m"
          limits:
            memory: "25Mi"
            cpu: "50m"
